<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <DefineConstants>GODOT</DefineConstants>
        <RootNamespace>SimpleFramework.GDExt</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Net\Net.csproj" />
      <ProjectReference Include="..\SimpleFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="GodotSharp" Version="4.5.1" />
    </ItemGroup>

</Project>
