<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DefineConstants>GODOT</DefineConstants>
        <RootNamespace>SimpleFramework.GDExt</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>..\bin\Debug\</OutputPath>
      <DefineConstants>GODOT</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>..\bin\Release\</OutputPath>
      <DefineConstants>GODOT</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Net\Net.csproj" />
      <ProjectReference Include="..\SimpleFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="GodotSharp" Version="4.5.1" />
    </ItemGroup>

</Project>
