<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SimpleFramework.Patterns</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Collections\Collections.csproj" />
      <ProjectReference Include="..\Utility\Utility.csproj" />
    </ItemGroup>

</Project>
