<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Toolkit</AssemblyName>
        <RootNamespace>SimpleFramework.Toolkit</RootNamespace>
    </PropertyGroup>
    
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>..\bin\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>..\bin\Release\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SimpleFramework.csproj" />
      <ProjectReference Include="..\Utility\Utility.csproj" />
    </ItemGroup>

</Project>
