<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SimpleFramework.Net</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Patterns\Patterns.csproj" />
      <ProjectReference Include="..\SimpleFramework.csproj" />
      <ProjectReference Include="..\Utility\Utility.csproj" />
    </ItemGroup>

</Project>
