<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SimpleFramework.Net</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Patterns\Patterns.csproj" />
      <ProjectReference Include="..\SimpleFramework.csproj" />
      <ProjectReference Include="..\Utility\Utility.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(GODOT)' == 'true'">
        <PackageReference Include="GodotSharp" Version="4.2.0" />
        <PackageReference Include="GodotSharpEditor" Version="4.2.0" Condition="'$(Configuration)' == 'Debug'" />
    </ItemGroup>

</Project>
